CREATE TABLE `Faculty`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(30) NOT NULL UNIQUE,

    CONSTRAINT `PK_FACULTY` PRIMARY KEY (`ID`)
);


CREATE TABLE `GROUPS`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(10) NOT NULL,
    `FACULTY_ID` INT NOT NULL,
    `HEAD_GROUP` INT,

    CONSTRAINT `pk_group` PRIMARY KEY (`ID`)
);


CREATE TABLE `LESSONS`(
    `GROUP_ID` INT NOT NULL,
    `PREPOD_ID` INT NOT NULL,
    `STUDY_ID` CHAR(20) NOT NULL,

    CONSTRAINT `Key3` PRIMARY KEY (`GROUP_ID`, `PREPOD_ID`, `STUDY_ID`)
);


CREATE TABLE `Prepods`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(120),
    `LAST_NAME` VARCHAR(120) NOT NULL,
    `FACULTY_ID` INT NOT NULL,

    CONSTRAINT `PK_PREPODS` PRIMARY KEY (`ID`)
);


CREATE TABLE `RATING`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `DATE` DATE NOT NULL,
    `PREPODS_ID` INT NOT NULL,
    `STUDENT_ID` INT NOT NULL,
    `STUDY_ID` CHAR(20) NOT NULL,
    `IS_ABSENT` CHAR(1) DEFAULT 'N',
    `VAL` INT,

    CONSTRAINT `PK_RATING` PRIMARY KEY (`ID`)
);


CREATE TABLE `Students`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `GROUP_ID` INT,
    `FIRST_NAME` VARCHAR(30),
    `LAST_NAME` VARCHAR(60) NOT NULL,

    CONSTRAINT `pk_students` PRIMARY KEY (`ID`)
);


CREATE TABLE `STUDY_LOAD`(
    `ID` CHAR(20) NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `Type_STUDY_ID` INT(10) NOT NULL,
    `hours` INT,

    CONSTRAINT `PK_STUDY_LOAD` PRIMARY KEY (`ID`)
);


CREATE TABLE `Subjects`(
    `ID` INT AUTO_INCREMENT,
    `NAME` VARCHAR(120),
    `FACULTY_ID` INT,

    CONSTRAINT `pk_subjects` PRIMARY KEY (`ID`)
);


CREATE TABLE `TYPE_STUDY_LOAD`(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(120)  NOT NULL UNIQUE,

    CONSTRAINT `PK_TYPE_stady_load` PRIMARY KEY (`ID`)
);


ALTER TABLE `GROUPS`
    ADD CONSTRAINT `fk_head_of_group`
    FOREIGN KEY (`HEAD_GROUP`) REFERENCES Students(`ID`),

    ADD CONSTRAINT `FK_FACULTY_GROUP`
    FOREIGN KEY (`FACULTY_ID`) REFERENCES Faculty(`ID`);


ALTER TABLE `LESSONS`
    ADD CONSTRAINT `FK_GROUP_LESSONS`
    FOREIGN KEY (`GROUP_ID`) REFERENCES GROUPS(`ID`),

    ADD CONSTRAINT `FK_PREPODS_LESSONS`
    FOREIGN KEY (`PREPOD_ID`) REFERENCES Prepods(`ID`),

    ADD CONSTRAINT `Relationship20`
    FOREIGN KEY (`STUDY_ID`) REFERENCES STUDY_LOAD(`ID`);


ALTER TABLE `Prepods`
    ADD CONSTRAINT `FK_STUDY_PREPODS`
    FOREIGN KEY (`FACULTY_ID`) REFERENCES Faculty(`ID`);


ALTER TABLE `RATING`
    ADD CONSTRAINT `FK_STUDENT_RATING`
    FOREIGN KEY (`STUDENT_ID`) REFERENCES Students(`ID`),

    ADD CONSTRAINT `FK_STUDY_LESSONS`
    FOREIGN KEY (`STUDY_ID`) REFERENCES STUDY_LOAD(`ID`),

    ADD CONSTRAINT `FK_PREPOD_RATING`
    FOREIGN KEY (`PREPODS_ID`) REFERENCES Prepods(`ID`);


ALTER TABLE `Students`
    ADD CONSTRAINT `fk_group_of students`
    FOREIGN KEY (`GROUP_ID`) REFERENCES GROUPS(`ID`);


ALTER TABLE `STUDY_LOAD`
    ADD CONSTRAINT `FK_SUBJECT_STUDY`
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES Subjects(`ID`),

    ADD CONSTRAINT `FK_TYPE_STUDY`
    FOREIGN KEY (`Type_STUDY_ID`) REFERENCES TYPE_STUDY_LOAD(`ID`);


ALTER TABLE `Subjects`
    ADD CONSTRAINT `FK_FACULTY_SUBJECTS`
    FOREIGN KEY (`FACULTY_ID`) REFERENCES Faculty(`ID`);
